// lang.js — HTORI ERP translations (EN / KR / ID)
const LANG = {
  EN: {
    "menu.dashboard": "Dashboard",
    "menu.order": "Order",
    "menu.mrp": "MRP",
    "menu.receiving": "Receiving",
    "menu.stock": "Stock",
    "menu.production": "Production",
    "menu.outsource": "Outsourcing",
    "menu.shipment": "Shipment",
    "menu.cost": "Cost",
    "menu.employees": "Employees",
    "menu.settings": "Settings",

    "employees.title": "Employees",
    "employees.form.title_add": "Add / Edit Employee",
    "employees.form.title_edit": "Edit Employee",
    "employees.form.empId": "Employee ID",
    "employees.form.name": "Name",
    "employees.form.role": "Role",
    "employees.form.type": "Employment Type",
    "employees.form.basicSalary": "Basic Salary",
    "employees.form.hourRate": "Hourly Rate",
    "employees.form.pieceRate": "Piece Rate",
    "employees.form.probation": "Probation",
    "employees.form.bankName": "Bank Name",
    "employees.form.bankAccount": "Bank Account",
    "employees.form.accountHolder": "Account Holder",
    "employees.form.taxNumber": "Tax Number (NPWP)",
    "employees.form.memo": "Memo",
    "employees.form.save": "Save",
    "employees.form.cancel": "Cancel",

    "employees.table.empId": "Emp ID",
    "employees.table.name": "Name",
    "employees.table.role": "Role",
    "employees.table.bank": "Bank",
    "employees.table.account": "Account",
    "employees.table.tax": "Tax No.",
    "employees.table.actions": "Actions",

    "notice.no_employees": "No employees",
    "notice.loading": "Loading..."
  },
  KR: {
    "menu.dashboard": "대시보드",
    "menu.order": "주문",
    "menu.mrp": "MRP",
    "menu.receiving": "입고",
    "menu.stock": "재고",
    "menu.production": "생산",
    "menu.outsource": "외주",
    "menu.shipment": "출고",
    "menu.cost": "원가",
    "menu.employees": "직원관리",
    "menu.settings": "설정",

    "employees.title": "직원관리",
    "employees.form.title_add": "직원 등록 / 수정",
    "employees.form.title_edit": "직원 정보 수정",
    "employees.form.empId": "사원번호",
    "employees.form.name": "이름",
    "employees.form.role": "역할",
    "employees.form.type": "고용형태",
    "employees.form.basicSalary": "기본급",
    "employees.form.hourRate": "시급",
    "employees.form.pieceRate": "개당단가",
    "employees.form.probation": "수습",
    "employees.form.bankName": "은행명",
    "employees.form.bankAccount": "계좌번호",
    "employees.form.accountHolder": "예금주명",
    "employees.form.taxNumber": "세금번호 (NPWP)",
    "employees.form.memo": "메모",
    "employees.form.save": "저장",
    "employees.form.cancel": "취소",

    "employees.table.empId": "사번",
    "employees.table.name": "이름",
    "employees.table.role": "역할",
    "employees.table.bank": "은행",
    "employees.table.account": "계좌",
    "employees.table.tax": "세금번호",
    "employees.table.actions": "작업",

    "notice.no_employees": "직원이 없습니다",
    "notice.loading": "로딩중..."
  },
  ID: {
    "menu.dashboard": "Dasbor",
    "menu.order": "Pesanan",
    "menu.mrp": "MRP",
    "menu.receiving": "Penerimaan",
    "menu.stock": "Stok",
    "menu.production": "Produksi",
    "menu.outsource": "Outsourcing",
    "menu.shipment": "Pengiriman",
    "menu.cost": "Biaya",
    "menu.employees": "Karyawan",
    "menu.settings": "Pengaturan",

    "employees.title": "Manajemen Karyawan",
    "employees.form.title_add": "Tambah / Edit Karyawan",
    "employees.form.title_edit": "Edit Karyawan",
    "employees.form.empId": "ID Karyawan",
    "employees.form.name": "Nama",
    "employees.form.role": "Peran",
    "employees.form.type": "Tipe Kerja",
    "employees.form.basicSalary": "Gaji Pokok",
    "employees.form.hourRate": "Gaji Per Jam",
    "employees.form.pieceRate": "Upah Per Item",
    "employees.form.probation": "Masa Percobaan",
    "employees.form.bankName": "Nama Bank",
    "employees.form.bankAccount": "No. Rekening",
    "employees.form.accountHolder": "Pemegang Rekening",
    "employees.form.taxNumber": "No. Pajak (NPWP)",
    "employees.form.memo": "Catatan",
    "employees.form.save": "Simpan",
    "employees.form.cancel": "Batal",

    "employees.table.empId": "ID",
    "employees.table.name": "Nama",
    "employees.table.role": "Peran",
    "employees.table.bank": "Bank",
    "employees.table.account": "Rekening",
    "employees.table.tax": "No. Pajak",
    "employees.table.actions": "Aksi",

    "notice.no_employees": "Tidak ada karyawan",
    "notice.loading": "Memuat..."
  }
};

// helper to read a translation key
function t(key) {
  return (LANG[window.lang] && LANG[window.lang][key]) ? LANG[window.lang][key] : key;
}
